### ISSUE TITLE
Seafile version 8.0.8

### ISSUE THREAD

**Issue by dimejo** [ggogel/seafile-containerized#29]
If possible please provide Seafile version 8.0.8. Seafile 9 is still declared as beta, hence I'm hesitant to use it.

**Comment by ggogel** [comment]
I didn't notice that there was a version 8.0.8 because the Seafile devs didn't put a notification for it on the forum. The images with the tag `8.0.8` should be available at any minute now on Dockerhub.

From my understanding, version 9.0.2 is considered stable and not beta. If there are any bugs, they are very likely related to the new golang fileserver, since this is actually one of the few new features. Though, the golang fileserver is disabled by default anyways and the old python-based is used. Other than that there were mostly dependency updates and minor tweaks here and there.

**Comment by ggogel** [comment]
I didn't notice that there was a version 8.0.8 because the Seafile devs didn't put a notification for it on the forum. The images with the tag `8.0.8` should be available at any minute now on Dockerhub.

From my understanding, version 9.0.2 is considered stable and not beta. If there are any bugs, they are very likely related to the new golang fileserver, since this is one of the few new features. Though, the golang fileserver is disabled by default anyway and the old python-based is used. Other than that there were mostly dependency updates and minor tweaks here and there.

**Comment by dimejo** [comment]
> The images with the tag `8.0.8` should be available at any minute now on Dockerhub.

They are already available on Docker Hub. Thanks for the fast update!

> From my understanding, version 9.0.2 is considered stable and not beta.

Versions 9.0.0. and 9.0.1 were marked as beta on the download and the [changelog site](https://manual.seafile.com/changelog/server-changelog/). Looks like they removed the beta tag with 9.0.2.
