### ISSUE TITLE
fail2ban

### ISSUE THREAD

**Issue by mibere** [ggogel/seafile-containerized#8]
Hello,

thanks a lot for your work, research and redesign, I like it more than the original. Keep on!

What do you think about integrating _fail2ban_? See https://manual.seafile.com/security/fail2ban/

**Comment by ggogel** [comment]
Hi,

thank you for the commendation.

You could maybe try to add this service to your deployment: https://github.com/crazy-max/docker-fail2ban

I think that integrating fail2ban into the deployment for everybody might be a bit overkill. Users might have already different security appliances implemented, such as a firewall. Another approach would definitely be to switch the Authentication provider altogether. So if you use LDAP or OAuth, you basically have anti-bruteforce mechanisms already integrated into the authentication provider, instead of putting another layer on top of it.
