### ISSUE TITLE
Things I noticed after the first start-up

### ISSUE THREAD

**Issue by mibere** [ggogel/seafile-containerized#9]
After I got it working today (Docker images as of 21. April) with [Caddy](https://caddyserver.com/) as reverse-proxy

- Firefox shows a yellow exclamation mark as the default user logo (`http://<domain>/media/avatars/default.png`) is served via HTTP (instead of HTTPS)
- with `HTTPS=true` in the docker-compose.yml `FILE_SERVER_ROOT`in the web interface was "https:...", but `SERVICE_URL` was "http:..."
- with `TIME_ZONE=Europe/Berlin` in the docker-compose.yml the time in the web interface seems to be UTC (2 hrs. behind actual time).
- In the docker log for the database (`docker logs seafile_db_1`) I see
```
2021-04-21 16:46:18 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'root' host: '<IP>' (Got an error reading communication packets)
2021-04-21 16:46:18 5 [Warning] Aborted connection 5 to db: 'ccnet_db' user: 'seafile' host: '<IP>' (Got an error reading communication packets)
2021-04-21 16:46:19 6 [Warning] Aborted connection 6 to db: 'seafile_db' user: 'seafile' host: '<IP>' (Got an error reading communication packets)
2021-04-21 16:46:19 7 [Warning] Aborted connection 7 to db: 'seahub_db' user: 'seafile' host: '<IP>' (Got an error reading communication packets)
2021-04-21 16:46:20 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'root' host: '<IP>' (Got an error reading communication packets)
```

_P.S. I'm new in Docker / Caddy / Seafile ;-)_

**Comment by ggogel** [comment]
> Firefox shows a yellow exclamation mark as the default user logo (http://<domain>/media/avatars/default.png) is served via HTTP (instead of HTTPS)

> with HTTPS=true in the docker-compose.yml FILE_SERVER_ROOTin the web interface was "https:...", but SERVICE_URL was "http:..."

I was able to reproduce the SERVICE_URL issue. I can't find where SERVICE_URL is configured in my project at least. I'd figure this is done by seafile-server on initial start up. I've even tried to set the variable `SEAFILE_SERVER_LETSENCRYPT=true`, which is used by the official docker deployment for https but the `SERVICE_URL` still ended up with http. I might have a look into this but it doesn't seem to be a major issue. As long as `FILE_SERVER_ROOT` is set to https it should be fine. Though this could explain the yellow exclamation mark, because the path to this is build from the `SERVICE_URL`. Simply set it to https and the warning should be gone.

The network on the application layer should look like this:
client <-- https --> your reverse proxy <-- http --> seafile-caddy <-- http --> seafile-server / seahub / seahub-media


> with TIME_ZONE=Europe/Berlin in the docker-compose.yml the time in the web interface seems to be UTC (2 hrs. behind actual time).

Did you set this environment variable after the first setup? Because the default is UTC if nothing is set. I wasn't able to reproduce this.

> In the docker log for the database (docker logs seafile_db_1) I see

Those are just warnings that connections were closed. This happens if one of the services is restarted or might even happen at other times. Anyway you can ignore them.

**Comment by ggogel** [comment]
@mibere Were you able to fix the issue with the ssl warning? Were I able to answer your questions?
